import React from "react";
import { createRoot } from "react-dom/client";
import "@fontsource/ibm-plex-sans/400.css";
import "@fontsource/ibm-plex-sans/500.css";
import "@fontsource/ibm-plex-mono/400.css";
import SocialContent from "./SocialContent.jsx";
import "../../design/tokens.css";
import "../../design/kit.css";
import "./style.css";
createRoot(document.getElementById("root")).render(<SocialContent />);
